function(add_unit_test test_name test_files)
    add_executable(unit-${test_name} ${test_files})
    message(STATUS "add unit-${test_name}")
endfunction()

aux_source_directory(./ unit_test_files)
foreach (test_file ${unit_test_files})
    get_filename_component(test_name ${test_file} NAME_WE)
    add_unit_test(${test_name} ${test_file})
endforeach ()
